#!/usr/bin/env python3

# ------------------------------------------------------- #
# Autogenerated, do not edit. All changes will be undone. #
# ------------------------------------------------------- #

from bs4 import BeautifulSoup
from urllib.request import urlopen
from datetime import datetime
from textwrap import wrap

PARSER = "html.parser"

def title_wrap(title:str):
    return "\n".join(wrap(title.strip(), 80))

def article_wrap(article:str):
    return "\n".join([wrap(line, 80, initial_indent="\t", subsequent_indent="\t")
                      for line in article.strip().split("\n")][0])

with urlopen("http://ceng.eskisehir.edu.tr/") as page:
    soup = BeautifulSoup(page, features=PARSER)

announcements = soup.find("table", {"id": "ContentPlaceHolder1_tickertable"})
announcements = {x.get_text(): x["href"] for x in announcements.find_all("a") }

with open("ceng_duyuru.txt", "w", encoding="utf-8") as file:
    now = datetime.now()
    file_title = "Announcement of C.ENG as of {}".format(now.strftime("%d.%m-%Y"))
    file.write(file_title+"\n"+len(file_title)*"-"+"\n\n")

    for title, link in announcements.items():
        # print("   ",link,"\t: ",title, sep="")
        with urlopen("http://ceng.eskisehir.edu.tr/"+link) as page:
            sub_soup = BeautifulSoup(page, features=PARSER)

        article_frame = sub_soup.find("td", {"class": "default-content"})
        art_title = article_frame.find("span", {"id":"ContentPlaceHolder1_lblBaslik"}).get_text()
        _content_frame = article_frame.find("span", {"id":"ContentPlaceHolder1_lblMetin"})
        art_content = "".join([x.get_text() for x in _content_frame.find_all("p")])

        art_title = title_wrap(art_title)
        art_content = "\n" + article_wrap(art_content)

        file.write(art_title +":" + art_content + "\n\n")
        print(art_title,":", art_content, "\n")

# END OF ceng_grabber__@19-01-11.py